name: eo_cog
channels:
  - conda-forge
  - rios
  - defaults
dependencies:
  - jupyter
  - numpy
  - pandas
  - pip
  - pip:
    - boto3==1.13.24
    - botocore==1.16.24
    - pyqt5-sip==4.19.18
    - pyqtwebengine==5.12.1
    - rasterio==1.1.5
    - requests==2.23.0
    - rio-tiler==2.0a11
    - s3transfer==0.3.3
