name: eo_cog
channels:
  - conda-forge
  - rios
  - defaults
dependencies:
  - jupyter=1.0.0=py_2
  - numpy=1.17.3=py37hde6bac1_0
  - pandas=0.25.3=py37h4f17bb1_0
  - pip:
    - boto3==1.13.24
    - botocore==1.16.24
    - pyqt5-sip==4.19.18
    - pyqtwebengine==5.12.1
    - rasterio==1.1.5
    - requests==2.23.0
    - rio-tiler==2.0a11
    - s3transfer==0.3.3
